// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFhNLV32mbtlP_-lABvYZIVXIfttlU2WQ',
    appId: '1:73174231270:android:7afa3c831517d6529fb327',
    messagingSenderId: '73174231270',
    projectId: 'commerce-pathshala',
    storageBucket: 'commerce-pathshala.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVmSsGMaz7ALUmqF13MzoFmsKDzpK8jw',
    appId: '1:73174231270:ios:70e43f20ee35771c9fb327',
    messagingSenderId: '73174231270',
    projectId: 'commerce-pathshala',
    storageBucket: 'commerce-pathshala.firebasestorage.app',
    androidClientId: '73174231270-omhrlejt78n0mbgf81mfirtb53epit6a.apps.googleusercontent.com',
    iosClientId: '73174231270-gng17bb1krc2t8rgc387pdf0tv5i8qqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.commercePaathshalaApp',
  );

}